[project]
name = "worth-it-temp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.6",
    "jinja2>=3.1.4",
    "numpy>=2.2.6",
    "numpy-financial>=1.0.0",
    "pandas>=2.3.1",
    "pandas-stubs>=2.3.0.250703",
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
    "scipy>=1.15.3",
    "uvicorn[standard]>=0.32.1",
]
